version: '3.9'

services:
  postgres:
    image: postgres:14
    container_name: db_app
    ports:
      - 5431:5432
    env_file:
      - enviroment/dev/.env
  app:
    container_name: go_webapp
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - postgres
    env_file:
      - enviroment/dev/.env
