version: '3.9'

services:
  postgres:
    container_name: postgres_godb
    command: -p 5432
    image: postgres:14-alpine
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=godb
      - DATABASE_HOST=localhost
    expose:
      - 5432

  app:
    container_name: go_webapp
    build:
      context: .
      dockerfile: docker/api/Dockerfile

    restart: always
    ports:
      - 8000:8000
    restart: on-failure
    volumes:
      - .:/app
    depends_on:
      - postgres
