version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: db_app
    command: -p 5432
    env_file:
      - .env.development
  app:
    container_name: go_webapp
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - postgres
    env_file:
      - .env.development
